#!/bin/sh

# Ejecuta gitleaks para verificar fugas de información
echo "Corriendo gitleaks para verificar información sensible..."

gitleaks detect --source . --no-git -v

if [ $? -ne 0 ]; then
  echo "Fugas de información detectadas. Commit abortado."
  exit 1
fi

echo "No se encontraron fugas. Procediendo con el commit."
exit 0
